const PDFDocument = require("pdfkit-table");

exports.generatePDF = function (connection, username, res) {

    // Create a new PDF document
    const doc = new PDFDocument({
        info: {
            Title: 'Cumulative Ongoing Tickets Report', //document title
            Author: username,
            Subject: 'All Time System Reporting',
            CreationDate: new Date()
        },
        margin: 30,
        size: 'Letter'
    });

    // Use a prepared statement with placeholders
    const query = 'SELECT * FROM FORM_TABLE WHERE status = ? OR status = ? ORDER BY full_name';
    const values = ['NEW', 'OPEN'];

    connection.query(query, values, (err, results) => {
        if (err) throw err;

        const tableHeaders = ['Email', 'Inquiry Number', 'Status'];

        const tableRows = results.map((row) => [
            row.email,
            row.inquiry_number,
            row.status,
        ]);

        const table = {
            title: "Cumulative Ongoing Tickets Report",
            //subtitle: "Subtitle",
            headers: [
                { label: tableHeaders[0], align: "center", },
                { label: tableHeaders[1], align: "center", },
                { label: tableHeaders[2], align: "center", },
            ],
            // simple data
            rows: [],
        };

        for (let i = 0; i < results.length; i++) {
            const row = results[i];
            const tableRow = [row.email, row.inquiry_number, row.status];
            table.rows.push(tableRow);
        }

        // the magic
        doc.table(table, {
            prepareHeader: () => doc.font("Times-Bold").fontSize(12),
            prepareRow: (row, indexColumn, indexRow, rectRow, rectCell, i) => {
                doc.font("Times-Roman").fontSize(12);
                indexColumn === 0 && doc.addBackground(rectRow, 'white', 0.15);
            },
        });
        const today = new Date();
        const datetime = today.toLocaleString();
        doc.text("Report generated by: " + username + " on " + datetime, {
            align: 'left'
        });

        // Set the appropriate headers for the file download
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=cumulative-ongoing-tickets_report.pdf');

        // Pipe the PDF document to the response
        doc.pipe(res);

        // Finalize the PDF document
        doc.end();

    });

}